### ISSUE TITLE
IJProgressView doesn't show

### ISSUE THREAD

**Issue by mitsus** [Isuru-Nanayakkara/IJProgressView#1]
Hi,
i've tried to add IJProgressView to my swift project, but i'm not able to show it.

I've call IJProgressView.shared.showProgressView(view) into viewDidLoad() before an syncronous http function and i stop it after this function...but i'm not able to show it.

Where are my errors?

Thanks and Regards

**Comment by ZaneH** [comment]
Can you show us a snippet?

**Comment by mitsus** [comment]
See Below

override func viewDidLoad() {
    super.viewDidLoad()

```
IJProgressView.shared.showProgressView(view)

var url:NSURL = NSURL(string: "http://www.xxxxx.xxx/api/xxx.php")!
var request:NSMutableURLRequest = NSMutableURLRequest(URL: url)
request.HTTPMethod = "GET"
request.setValue("application/json", forHTTPHeaderField: "Accept")
var reponseError: NSError?
var response: NSURLResponse?
var urlData: NSData? = NSURLConnection.sendSynchronousRequest(request, returningResponse:&response, error:&reponseError)

if ( urlData != nil ) {            
let res = response as NSHTTPURLResponse!;
    if (res.statusCode >= 200 && res.statusCode < 300){

var responseData:NSString  = NSString(data:urlData!, encoding:NSUTF8StringEncoding)!
    var error: NSError?
    let jsonData:NSDictionary = NSJSONSerialization.JSONObjectWithData(urlData!, options:NSJSONReadingOptions.MutableContainers , error: &error) as NSDictionary
    ....................
    ....................
   }
```

   }
} else {  
            var alertView:UIAlertView = UIAlertView() 
            alertView.title = "Sync Failed!"
            alertView.message = "Connection Failure"
            if let error = reponseError {
                alertView.message = (error.localizedDescription)
            }
            alertView.delegate = self
            alertView.addButtonWithTitle("OK")
            alertView.show()
   }
IJProgressView.shared.hideProgressView()
}

**Comment by ZaneH** [comment]
Have you looked into making the request asynchronous? Whenever you create an asynchronous request your app remains responsive, and you're still able to run code whenever you recieve data by using one of <a href="https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLConnectionDataDelegate_protocol/index.html#//apple_ref/occ/intf/NSURLConnectionDataDelegate">NSURLConnectionDelegate's many protocols.</a> like:
`func connection(connection: NSURLConnection, didReceiveData data: NSData) { ... }`

This also removes a lot of confusion with synchronous requests.

**Comment by mitsus** [comment]
Ok. I've change Syncronous with Async request. This is my full code. I use also a tableview....but your ProgressView doesn't work.

override func viewDidLoad() {

```
    super.viewDidLoad()

    IJProgressView.shared.showProgressView(view)

    var url:NSURL = NSURL(string: "http://www.xxxxx.xxx/api/xxx.php")!
    var request:NSMutableURLRequest = NSMutableURLRequest(URL: url)

    request.HTTPMethod = "GET"

    request.setValue("application/json", forHTTPHeaderField: "Accept")
    var reponseError: NSError?        
    var response: NSURLResponse?


    NSURLConnection.sendAsynchronousRequest(request, queue: NSOperationQueue.mainQueue(), completionHandler: {
        response, data, error in

        if (error != nil) {
            return
        }

        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
            var error: NSError?

                       self.dati = (NSJSONSerialization.JSONObjectWithData(data, options: .MutableContainers, error: &error) as NSDictionary)["spots"] as NSMutableArray

                       if (error != nil){
                                return
                       }

            ..................

                dispatch_async(dispatch_get_main_queue()){
                    ..... ...... ....... . ........
                }
     }
```

   })
   IJProgressView.shared.hideProgressView()
    }

```
func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return array.count    
}

func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell: ViewCell = tableView.dequeueReusableCellWithIdentifier("Cell") as ViewCell
    ..................

    return cell

}
```

**Comment by ZaneH** [comment]
It's still doing exactly what it's supposed to do. Let me step you through your code, maybe it'll make more since and hopefully help solve the problem.
- Shows the progress view
- Sets up all the variables and information for the web request
- Sends an asynchronous request to the main queue with a block that will run on completion
- Hides the progress view

## 

Keep in mind that there's no pause in all of this, all of it is executed very quickly meaning your `IJProgressView.shared.showProgressView(view)` and `IJProgressView.shared.hideProgressView()` are called nearly at the same time. I recommend you put the `IJProgressView.shared.hideProgressView()` in your completion block, but there are other ways to do this still.

**Comment by mitsus** [comment]
Dear ZaneH,
thanks a lot for your support. Now your Activity Indicator just work fine.
I've solve problems. I've put showProgressView into AsyncronousRequest and hideProgressView into main UI executed after Asyncronous Request.
Below my correct code:

```
     NSURLConnection.sendAsynchronousRequest(request, queue:   NSOperationQueue.mainQueue(), completionHandler: {
                   response, data, error in

        if (error != nil) {
            return
        }
        IJProgressView.shared.showProgressView(self.view)
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
                   ............ Async Code .........
                   dispatch_async(dispatch_get_main_queue()){
                               .......... Main UI Code ........
                                IJProgressView.shared.hideProgressView()
                            }
         }
     })
```
