### ISSUE TITLE
Starts with a delay 

### ISSUE THREAD

**Issue by ali-asad-saeed** [Isuru-Nanayakkara/IJProgressView#3]
IJprogressView Starts with a delay which shows the apps hangs . Why is it like so ?
To show the progressView
IJProgressView.shared.showProgressView(view: self.view)
To Hide the ProgressView
IJProgressView.shared.hideProgressView()

**Comment by Isuru-Nanayakkara** [comment]
@heavyBug Sorry for the late reply.

Are you executing any background tasks? If so, you have to show/hide the progress view in the main thread.
