### ISSUE TITLE
'shared' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Bitcosoftware** [Isuru-Nanayakkara/IJProgressView#6]
I updated my POD today and now I am getting this error everywhere I am trying to show or hide the progress view.  Did something change?

**Comment by vkcldhkd** [comment]
I have the same problem...

**Comment by AamirSk** [comment]
Facing the same issue.. Any solution for this?

**Comment by kaiserfenix** [comment]
if anyone's still having issues, i was able to "fix" it by changing:
`static let shared = IJProgressView()` to 
`public static let shared = IJProgressView() `

(simply adding a public keyword) to it. seems that before, the default was 'public' but now it's a protection level that's a little more restricted.

after, you'll have to change any of the `IJProgressView.shared.showProgressView(self.view)` calls to just `IJProgressView.shared.showProgressView()` (don't pass in the self.view as this function technically takes no arguments).
